#inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Rails/TimeZone:
  Exclude:
    - 'spec/**/*'

Rails/HttpPositionalArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false