version: '2'
services:
  db:
    image: postgres
  web:
    image: koduki/example-todo
    ports:
      - 3000:3000
    volumes:
      - "$PWD:/usr/src/app"
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/postgres
    depends_on:
      - db